name: Bump

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  lint:
    name: Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm
      - name: Remove node_modules
        run: rm -rf **/node_modules/
      - name: Remove package-lock.json
        run: rm -rf **/package-lock.json
      - name: Install Dependencies
        run: npm install
      - name: 'Create Pull Request'
        env:
          COMMIT_MESSAGE: 'chore(bot): bump dependencies'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: ${{ env.COMMIT_MESSAGE }}
          signoff: true
          delete-branch: true
          title: ${{ env.COMMIT_MESSAGE }}
