name: Pull Requests Auto-Merge
on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: >
      github.actor == 'dependabot[bot]' ||
      (
        github.actor == github.repository_owner &&
        github.event.pull_request.user.login == 'github-actions[bot]' &&
        startsWith(github.event.pull_request.title, 'chore(bot)') &&
        endsWith(github.event.pull_request.title, 'bump dependencies')
      )
    steps:
      - name: Auto-merge Pull Requests
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
