# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request

name: Pull Requests Auto-Merge
on:
  workflow_call:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: >
      github.actor == 'dependabot[bot]' ||
      (
        github.actor == github.repository_owner &&
        (
          github.event.pull_request.user.login == 'github-actions[bot]' ||
          github.event.pull_request.user.login == github.repository_owner
        ) &&
        startsWith(github.event.pull_request.title, 'chore(bot)') &&
        endsWith(github.event.pull_request.title, 'bump dependencies')
      )
    steps:
      - name: Auto-merge Pull Requests
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
