name: test
on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '30 5 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo actor ${{github.actor}}
          echo repository_owner ${{github.repository_owner}}
          echo pull_request.title ${{github.event.pull_request.title}}
          echo pull_request.user.login ${{github.event.pull_request.user.login}}
          echo pull_request.user.name ${{github.event.pull_request.user.name}}
