name: test
on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '30 5 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: actor
        run: echo ${{github.actor}}

      - name: repository_owner
        run: echo ${{github.repository_owner}}

      - name: pull_request.title
        run: echo ${{github.event.pull_request.title}}

      - name: pull_request.user
        run: echo ${{github.event.pull_request.user}}
