name: test
on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: actor
        run: echo ${{github.actor}}

      - name: actor_id
        run: echo ${{github.actor_id}}
